#
# This config file is loadded **ONLY** in local development.
# It will be replaced by a config/config.json request when served with wire app serve.
#

app:
  name: 'Teamwork'
client:
  keyStorage:
    root: "dxos/teamwork-local/keys"
  feedStorage:
    root: "dxos/teamwork-local/feeds"
