#
# This config file is loadded **ONLY** in local development.
# It will be replaced by a config/config.json request when served with wire app serve.
#

app:
  name: Teamwork
storagePath: dxos/teamwork-local
storageType: persistent
wns:
  server: "https://wns1.kube.moon.dxos.network/api"
  chainId: "devnet-2"
sentry:
  dsn: http://c4520c11e2c14d799a2802f59495ac49@134.122.22.117:9000/2
  environment: development
