#
# App-specific constants and defaults.
#

app:
  name: 'Teamwork'
  rootElement: 'root'

devtools: true

client:
  keyStorage:
    root: "dxos/apps/keys"

  feedStorage:
    root: "dxos/apps/feeds"

  swarm:
    signal: "wss://demo.kube.dxos.network/dxos/signal"
    ice:
      - urls: "stun:stun.wirelne.ninja:3478"
      - urls: "turn:stun.wireline.ninja:3478"
        username: "wireline"
        credential: "wireline"

services:
  wns:
    server: "https://wns1.kube.moon.dxos.network/api"
    chainId: "devnet-2"
  ipfs:
    server: "https://apollo1.kube.moon.dxos.network/dxos/ipfs/api"
    gateway: "https://apollo1.kube.moon.dxos.network/dxos/ipfs/gateway/"

debug:
    mode: 'development'
