#
# App-specific constants and defaults.
#

app:
  name: 'Teamwork'
  rootElement: 'root'

devtools: true
snapshots: true

storagePath: dxos/teamwork-v1
storageType: persistent

swarm:
  signal: "wss://apollo1.kube.moon.dxos.network/dxos/signal"
  ice:
    - urls: "turn:stun.wireline.ninja:3478"
      username: "wireline"
      credential: "wireline"
wns:
  server: "https://wns1.kube.moon.dxos.network/api"
  chainId: "devnet-2"
ipfs:
  server: "https://apollo1.kube.moon.dxos.network/dxos/ipfs/api"
  gateway: "https://apollo1.kube.moon.dxos.network/dxos/ipfs/gateway/"

debug:
  mode: 'development'
  logging: '*:warn,*:error'

sentry:
  dsn: https://296be949e8ea4f69800a4031847f205b@sentry.kube.dxos.network/2
  environment: production
