#
# App-specific constants and defaults.
#

app:
  name: 'Teamwork'
  rootElement: 'root'

devtools: true
snapshots: true

storage:
  persistent: true
  path: dxos/teamwork-v2

swarm:
  signal: "wss://apollo2.kube.moon.dxos.network/dxos/signal"
  ice:
    - urls: "turn:apollo2.kube.moon.dxos.network:3478"
      username: "dxos"
      credential: "dxos"
wns:
  server: "https://wns1.kube.moon.dxos.network/api"
  chainId: "devnet-2"
ipfs:
  server: "https://apollo2.kube.moon.dxos.network/dxos/ipfs/api"
  gateway: "https://apollo2.kube.moon.dxos.network/dxos/ipfs/gateway/"

debug:
  mode: 'development'
  # logging: '*:warn,*:error'
  logging: 'DXOS*'

sentry:
  dsn: https://296be949e8ea4f69800a4031847f205b@sentry.kube.dxos.network/2
  environment: production
