#
# App-specific constants and defaults.
#

app:
  name: 'Teamwork'
  rootElement: 'root'

devtools: true

storagePath: dxos/teamwork-v1
storageType: persistent

swarm:
  signal: "wss://apollo1.kube.moon.dxos.network/dxos/signal"
  ice:
    - urls: "turn:stun.wireline.ninja:3478"
      username: "wireline"
      credential: "wireline"
wns:
  server: "https://wns1.kube.moon.dxos.network/api"
  chainId: "devnet-2"
ipfs:
  server: "https://apollo1.kube.moon.dxos.network/dxos/ipfs/api"
  gateway: "https://apollo1.kube.moon.dxos.network/dxos/ipfs/gateway/"

debug:
    mode: 'development'

sentry:
  dsn: http://c4520c11e2c14d799a2802f59495ac49@134.122.22.117:9000/2
