
#
# Copyright 2019 Wireline, Inc.
#
# Javascript Node CircleCI 2.0 configuration file.
# https://circleci.com/docs/2.0/language-javascript
#

version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.16

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v0.1.2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v0.1.2-dependencies-

      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v0.1.2-dependencies-{{ checksum "package.json" }}
