#
# Environment config.
#

client:
  swarm:
    signal: "wss://wireline-signal-ws.herokuapp.com/"
    ice:
      - urls: "stun:stun.wirelne.ninja:3478"
      - urls: "turn:stun.wireline.ninja:3478"
        username: "wireline"
        credential: "wireline"
