#
# Environment config.
#

client:
  swarm:
    signal: "wss://signal2.dxos.network/dxos/signal"
    ice:
      - urls: "stun:stun.wirelne.ninja:3478"
      - urls: "turn:stun.wireline.ninja:3478"
        username: "wireline"
        credential: "wireline"
