#
# Environment config.
#

client:
  swarm:
    signal: "ws://127.0.0.1:4000"
    ice:
      - urls: "stun:127.0.0.1:3478"
      - urls: "turn:127.0.0.1:3478"
        username: "wireline"
        credential: "wireline"
