name: CI

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 18
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.1
      - name: Build and test
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          yarn install --frozen-lockfile
          yarn build
          yarn lint
          yarn lint:lockfile
          yarn version:check
          yarn dist --scope '@dxos/teamwork-app'
      - run: |
          yarn test:coverage
          # The c8 tool leaves tmp folder which is large, we don't want it uploaded to artifacts
          rm -rf coverage/tmp
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage
      - name: Playwright tests
        run: |
          yarn playwright
      - uses: actions/upload-artifact@v2
        with:
          name: playwright-video
          path: apps/teamwork-app/tests/playwright/videos
