name: CI

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build and test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn lint
          yarn lint:lockfile
          yarn lint:version
          yarn dist --scope '@dxos/teamwork'
      - run: |
          yarn test:coverage
          # The c8 tool leaves tmp folder which is large, we don't want it uploaded to artifacts
          rm -rf coverage/tmp
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage
      - name: Playwright tests
        run: |
          yarn start & 
          set +e
          i=0
          until curl "http://localhost:8080" | grep -q "Teamwork"
          do
            ((i++))
            if [ "$i" -gt 30 ]
            then
              exit -1
            fi
            echo "Sleeping..."
            sleep 3
          done
          yarn playwright
